models:
  Generator:
    name: "UNet3D"
    type: "UNet3D"
    params:
      feature_maps: 64
      in_channels: 1
      out_channels: 1
      num_levels: 4
      conv_kernel_size: 3
      pool_kernel_size: 2
      pooling_type: "MaxPool3d"
      num_groups: !!null
      padding: !python/tuple [1, 1, 1, 1, 1, 1]
      activation: "ReLU"
      interpolation: True
      scale_factor: !python/tuple [2, 2, 2] # Used as the multiplier for the image H/W/D in torch.nn.Upsample or as stride in case of ConvTranspose3d, must reverse the MaxPool3d operation from the corresponding encoder.
    optimizer:
      type: "FusedSGD"
      params:
        lr: 0.000001
        momentum: 0.9
        weight_decay: 0.1
    scheduler:
      type: "MultiStepLR"
      params:
        milestones: [75, 100]
        gamma: 0.1
    criterion:
      MSELoss:
        type: "MSELoss"
    metrics:
      Accuracy:
        type: "Accuracy"

  Segmenter:
    name: "UNet3D"
    type: "UNet3D"
    params:
      feature_maps: 64
      in_channels: 1
      out_channels: 4
      num_levels: 4
      conv_kernel_size: 3
      pool_kernel_size: 2
      pooling_type: "MaxPool3d"
      num_groups: !!null
      padding: !python/tuple [1, 1, 1, 1, 1, 1]
      activation: "Leaky_ReLU"
      interpolation: True
      scale_factor: !python/tuple [2, 2, 2] # Used as the multiplier for the image H/W/D in torch.nn.Upsample or as stride in case of ConvTranspose3d, must reverse the MaxPool3d operation from the corresponding encoder.
    optimizer:
      type: "FusedSGD"
      params:
        lr: 0.001
        momentum: 0.9
        weight_decay: 0.001
    scheduler:
      type: "ReduceLROnPlateau"
      params:
        mode: "min"
        factor: 0.1
        patience: 3
    criterion:
      DiceLoss:
        type: "DiceLoss"
        params:
          reduction: !!null
          ignore_index: -100
          weight: !torch/tensor [0.22, 0.28, 0.235, 0.265]
    metrics:
      Dice:
        type: "Dice"
        params:
          num_classes: 4
          reduction: !!null
          ignore_index: 0
          average: !!null
          weight: !!null
      IoU:
        type: "IoU"
        params:
          num_classes: 4
          reduction: !!null
          ignore_index: 0
          average: !!null
          weight: !!null
      Accuracy:
        type: "Accuracy"
      Precision:
        type: "Precision"
        params:
          average: True
      Recall:
        type: "Recall"
        params:
          average: True

  Discriminator:
    name: "ResNet3D"
    type: "ResNet18"
    params:
      in_channels: 1
      out_channels: 4
      num_groups: !!null
      conv_groups: 1
      width_per_group: 64
      padding: !!null
      activation: "ReLU"
      zero_init_residual: False
      replace_stride_with_dilation: !!null
    optimizer:
      type: "FusedSGD"
      params:
        lr: 0.0001
        momentum: 0.9
        weight_decay: 0.1
    scheduler:
      type: "MultiStepLR"
      params:
        milestones: [30, 60, 90]
        gamma: 0.1
    criterion:
      NLLLoss:
        type: "NLLLoss"
        params:
    metrics:
      Accuracy:
        type: "Accuracy"
      Precision:
        type: "Precision"
        params:
          average: True
      Recall:
        type: "Recall"
        params:
          average: True

dataset:
  iSEG:
    path: "/data/users/pldelisle/datasets/Preprocessed/iSEG/Training/Patches/Aligned/Full"
    modalities: "T1"
    max_subjects: !!null
    validation_split: 0.2
  MRBrainS:
    path: "/data/users/pldelisle/datasets/Preprocessed/MRBrainS/TrainingData/Patches/Aligned/Full"
    modalities: "T1_1mm"
    max_subjects: !!null
    validation_split: 0.2
  ABIDE:
    path: "/data/users/pldelisle/datasets/ABIDE/freesurfer"
    modalities: "T1"
    max_subjects: !!null
    max_num_patches: 15000
    validation_split: 0.2
    sites: !!null

training:
  batch_size: 24
  nb_epochs: 125
  patience_segmentation: 3
  data_augmentation: False
  variables:
    disc_ratio: 0.75
    seg_ratio: 1.0
    train_generator_every_n_steps: 1
    train_generator_every_n_steps_seg: 1

visdom:
  server: "10.180.113.44"
  port: "8097"
  env: "deepNormalize_phoebe_disc_ratio_0_75"

logger:
  path: "/tmp/ml/tests"
  log_after_iterations: 50
